# Generated by Django 3.1.7 on 2021-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_Pics'),
        ),
    ]
